https://lookerstudio.google.com/c/reporting/create?c.mode=edit&c.reportId=REPORT_ID&
r.reportName=REPORT_NAME&
ds.*.refreshFields=false&

ds.h_adgroups.connector=bigQuery&
ds.h_adgroups.datasourceName=h_adgroups&
ds.h_adgroups.projectId=YOUR_PROJECT_ID&
ds.h_adgroups.type=TABLE&
ds.h_adgroups.datasetId=YOUR_DATASET_ID&
ds.h_adgroups.tableId=hagakure_adgroups&

ds.h_campaigns.connector=bigQuery&
ds.h_campaigns.datasourceName=h_campaigns&
ds.h_campaigns.projectId=YOUR_PROJECT_ID&
ds.h_campaigns.type=TABLE&
ds.h_campaigns.datasetId=YOUR_DATASET_ID&
ds.h_campaigns.tableId=hagakure_campaigns&

ds.rsa_to_remove.connector=bigQuery&
ds.rsa_to_remove.datasourceName=rsa_to_remove&
ds.rsa_to_remove.projectId=YOUR_PROJECT_ID&
ds.rsa_to_remove.type=TABLE&
ds.rsa_to_remove.datasetId=YOUR_DATASET_ID&
ds.rsa_to_remove.tableId=rsa_to_remove&

ds.rsa_count.connector=bigQuery&
ds.rsa_count.datasourceName=rsa_count&
ds.rsa_count.projectId=YOUR_PROJECT_ID&
ds.rsa_count.type=TABLE&
ds.rsa_count.datasetId=YOUR_DATASET_ID&
ds.rsa_count.tableId=rsa_count&

ds.qs_rec.connector=bigQuery&
ds.qs_rec.datasourceName=qs_rec&
ds.qs_rec.projectId=YOUR_PROJECT_ID&
ds.qs_rec.type=TABLE&
ds.qs_rec.datasetId=YOUR_DATASET_ID&
ds.qs_rec.tableId=quality_score_recommendations&

ds.imp_share_rec.connector=bigQuery&
ds.imp_share_rec.datasourceName=imp_share_rec&
ds.imp_share_rec.projectId=YOUR_PROJECT_ID&
ds.imp_share_rec.type=TABLE&
ds.imp_share_rec.datasetId=YOUR_DATASET_ID&
ds.imp_share_rec.tableId=imp_share_recommendations&

ds.ad_str.connector=bigQuery&
ds.ad_str.datasourceName=ad_str&
ds.ad_str.projectId=YOUR_PROJECT_ID&
ds.ad_str.type=TABLE&
ds.ad_str.datasetId=YOUR_DATASET_ID&
ds.ad_str.tableId=ad_group_ad&

ds.qs_view.connector=bigQuery&
ds.qs_view.datasourceName=qs_view&
ds.qs_view.projectId=YOUR_PROJECT_ID&
ds.qs_view.type=TABLE&
ds.qs_view.datasetId=YOUR_DATASET_ID&
ds.qs_view.tableId=quality_score_view&

ds.ai_max_sum.connector=bigQuery&
ds.ai_max_sum.datasourceName=ai_max_sum&
ds.ai_max_sum.projectId=YOUR_PROJECT_ID&
ds.ai_max_sum.type=TABLE&
ds.ai_max_sum.datasetId=YOUR_DATASET_ID&
ds.ai_max_sum.tableId=ai_max_summary&

ds.ectr_view.connector=bigQuery&
ds.ectr_view.datasourceName=ectr_view&
ds.ectr_view.projectId=YOUR_PROJECT_ID&
ds.ectr_view.type=TABLE&
ds.ectr_view.datasetId=YOUR_DATASET_ID&
ds.ectr_view.tableId=ectr_view&

ds.h_lp.connector=bigQuery&
ds.h_lp.datasourceName=h_lp&
ds.h_lp.projectId=YOUR_PROJECT_ID&
ds.h_lp.type=TABLE&
ds.h_lp.datasetId=YOUR_DATASET_ID&
ds.h_lp.tableId=hagakure_landing_pages&

ds.kp.connector=bigQuery&
ds.kp.datasourceName=kp&
ds.kp.projectId=YOUR_PROJECT_ID&
ds.kp.type=TABLE&
ds.kp.datasetId=YOUR_DATASET_ID&
ds.kp.tableId=keyword_performance&

ds.h_keywords.connector=bigQuery&
ds.h_keywords.datasourceName=h_keywords&
ds.h_keywords.projectId=YOUR_PROJECT_ID&
ds.h_keywords.type=TABLE&
ds.h_keywords.datasetId=YOUR_DATASET_ID&
ds.h_keywords.tableId=hagakure_keywords&

ds.ar_view.connector=bigQuery&
ds.ar_view.datasourceName=ar_view&
ds.ar_view.projectId=YOUR_PROJECT_ID&
ds.ar_view.type=TABLE&
ds.ar_view.datasetId=YOUR_DATASET_ID&
ds.ar_view.tableId=ar_view&

ds.lpe_view.connector=bigQuery&
ds.lpe_view.datasourceName=lpe_view&
ds.lpe_view.projectId=YOUR_PROJECT_ID&
ds.lpe_view.type=TABLE&
ds.lpe_view.datasetId=YOUR_DATASET_ID&
ds.lpe_view.tableId=lpe_view&

ds.ad_group_ad.connector=bigQuery&
ds.ad_group_ad.datasourceName=ad_group_ad&
ds.ad_group_ad.projectId=YOUR_PROJECT_ID&
ds.ad_group_ad.type=TABLE&
ds.ad_group_ad.datasetId=YOUR_DATASET_ID&
ds.ad_group_ad.tableId=ad_group_ad&

ds.kw_view.connector=bigQuery&
ds.kw_view.datasourceName=kw_view&
ds.kw_view.projectId=YOUR_PROJECT_ID&
ds.kw_view.type=TABLE&
ds.kw_view.datasetId=YOUR_DATASET_ID&
ds.kw_view.tableId=keyword_performance_view&

ds.sum_imp_grow.connector=bigQuery&
ds.sum_imp_grow.datasourceName=sum_imp_grow&
ds.sum_imp_grow.projectId=YOUR_PROJECT_ID&
ds.sum_imp_grow.type=TABLE&
ds.sum_imp_grow.datasetId=YOUR_DATASET_ID&
ds.sum_imp_grow.tableId=summary_impression_grow
